# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3c9e1e518d7d1f90cc5fa3703ae3216f95f10a68334b1706e5e578def6bb9b6530ad018494291b7623031ef15bfbb4e606ebc61be9ba3c1c2a1bd8b181a241a

test:
  secret_key_base: 467717c243f80fb43a850bc675f1394dedaad1b499640323249a4fb8b691e84c4889358d66d6037460c3f73572a738dd583976615c5fa1bd6aaf93df1af15191

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
